"""add employees table and clinic employees_scraped_at

Revision ID: ec7df11e0b31
Revises: i0a1b2c3d456
Create Date: 2026-03-21 21:14:14.440279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec7df11e0b31'
down_revision: Union[str, Sequence[str], None] = 'i0a1b2c3d456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=256), nullable=False),
    sa.Column('linkedin_url', sa.String(length=512), nullable=False),
    sa.Column('position_title', sa.String(length=1024), nullable=True),
    sa.Column('company_name', sa.String(length=512), nullable=True),
    sa.Column('review_status', sa.String(length=16), nullable=False),
    sa.Column('raw_profile', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id', 'linkedin_url', name='uq_employee_clinic_linkedin')
    )
    op.add_column('clinics', sa.Column('employees_scraped_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinics', 'employees_scraped_at')
    op.drop_table('employees')
    # ### end Alembic commands ###
